spring.application.name=practica9
spring.mongodb.uri=mongodb+srv://andresmenduina_db_user:h4ncITppaK0qy482@accesoadatos.1q0y1co.mongodb.net/practica9?retryWrites=true&w=majority&appName=AccesoADatos


